<?php

/**
 * Implements hook_menu().
 */
function cstore_menu() {
  $items['admin/config/cstore'] = array(
    'title' => 'Cup cakes store settings',
    'description' => 'Cupcakes store settings',
    'position' => 'left',
    'weight' => -100,
    'page callback' => 'system_admin_menu_block_page',
    'access arguments' => array('administer site configuration'),
    'file' => 'system.admin.inc',
    'file path' => drupal_get_path('module', 'system'),
  );
  
  $items['admin/config/cstore/settings'] = array(
    'title' => 'General settings',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('cstore_admin_form'),
    'access arguments' => array('cstore admin'),
    'file' => 'cstore.admin.inc',
  );
  
  $items['admin/config/cstore/theming'] = array(
    'title' => 'Theming settings',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('cstore_admin_theming_form'),
    'access arguments' => array('cstore admin'),
    'file' => 'cstore.admin.inc',
  );
  
  $items['cart'] = array(
    'title' => 'Your shopping cart',
    'description' => 'The shopping cart page',
    'page callback' => 'basic_cart_cart',
    'access arguments' => array('use basic cart'),
    'type' => MENU_CALLBACK,
    'file' => 'basic_cart.cart.inc',
  );

  $items['cart/add'] = array(
    'title' => 'Add to cart',
    'description' => 'Add to cart url.',
    'page callback' => 'basic_cart_add_to_cart',
    'access arguments' => array('use basic cart'),
    'type' => MENU_CALLBACK,
    'file' => 'basic_cart.cart.inc',
  );

  $items['cart/remove'] = array(
    'title' => 'Remove from cart',
    'description' => 'Remove from cart url.',
    'page callback' => 'basic_cart_remove_from_cart',
    'access arguments' => array('use basic cart'),
    'type' => MENU_CALLBACK,
    'file' => 'basic_cart.cart.inc',
  );
  
  return $items;
}


/**
 * Returns the fields we need to create.
 * 
 * @return mixed
 *   Key / Value pair of field name => field type. 
 */
function cstore_get_fields() {
  return array(
    // TODO: Allow sending settings like number of items
    'field_ingredients' => array(
      'type' => 'text',
      'title' => t('Ingredients'),
      'description' => t('Please enter the list of ingredients.'),
    ),
    'field_price' => array(
      'type' => 'number_decimal',
      'title' => t('Price'),
      'description' => t('Please enter this item\'s price.'),
    ),
    'field_discount' => array(
      'type' => 'number_integer',
      'title' => t('Discount'),
      'description' => t('Please enter this item\'s discount.'),
    ),
    'field_add_to_cart' => array(
      'type' => 'text',
      'title' => 'Add to cart',
      'description' => '',
    ),
  );
}


/**
 * Helper function. Returns an array of types.
 */ 
function cstore_product_types(){
  static $types;
  
  if (empty($types)) {
    $types = variable_get('cstore_content_types', array());
  }
    
  return $types;
}